### ISSUE TITLE
dependency issues wgbs

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#1044]
Hallo all,
This happens :
```bash
Creating environment from /home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/site-packages/snakePipes/shared/rules/envs/wgbs.yaml in /home/tgeorgom/mambaforge/envs
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
mpi-ie/linux-64                                    906.0 B @   3.0kB/s  0.3s
mpi-ie/noarch                                        2.9kB @   4.8kB/s  0.6s


Looking for: ['bwameth=0.2.2', 'samtools', 'methyldackel=0.5.0', 'metilene=0.2.8', 'bedtools=2.29.2', 'r-base=3.6.3', 'r-car=3.0_6', 'r-factominer=2.2', 'r-ggplot2=3.1.1', 'r-rmarkdown', 'r-dplyr=1.0.2', 'r-tidyr', 'r-pander', 'r-factominer', 'bioconductor-bsseq', 'bioconductor-genomicranges=1.38.0', 'bioconductor-genomicfeatures=1.38.0', 'bioconductor-biomart=2.42.0', 'bioconductor-dss=2.34.0', 'bioconductor-dmrseq=1.6.0', 'bioconductor-rtracklayer=1.46.0', 'bioconductor-biocparallel=1.20.0']


Could not solve for environment specs
The following packages are incompatible
├─ r-base 3.6.3**  is requested and can be installed;
└─ r-ggplot2 3.1.1**  is uninstallable because it requires
   └─ r-base >=3.5.1,<3.5.2.0a0 , which conflicts with any installable versions previously reported.
Traceback (most recent call last):
  File "/home/tgeorgom/mambaforge/envs/snakePipes/bin/snakePipes", line 377, in createCondaEnvs
    subprocess.check_call(cmd)
  File "/home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mamba', 'env', 'create', '--force', '--file', '/home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/site-packages/snakePipes/shared/rules/envs/wgbs.yaml', '--name', '98cbb2db25fd7c2388074d1f0668a233']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tgeorgom/mambaforge/envs/snakePipes/bin/snakePipes", line 460, in <module>
    main(sys.argv[1:])
  File "/home/tgeorgom/mambaforge/envs/snakePipes/bin/snakePipes", line 454, in main
    createCondaEnvs(args)
  File "/home/tgeorgom/mambaforge/envs/snakePipes/bin/snakePipes", line 380, in createCondaEnvs
    shutil.rmtree(os.path.join(condaDirUse, h), ignore_errors=False)
  File "/home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/shutil.py", line 759, in rmtree
    _rmtree_safe_fd(stack, onexc)
  File "/home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
    onexc(func, path, err)
  File "/home/tgeorgom/mambaforge/envs/snakePipes/lib/python3.12/shutil.py", line 669, in _rmtree_safe_fd
    orig_st = os.lstat(name, dir_fd=dirfd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sunta3iouxos** [comment]
can be solved by:
`r-ggplot2=3.2`

**Comment by katsikora** [comment]
Hi,
which snakePipes version does this happen with?

Best wishes,

Katarzyna

**Comment by sunta3iouxos** [comment]
This is what I get:
```bash
snakePipes version
version 2.5.3
```

```R
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 23.10

Matrix products: default
BLAS/LAPACK: /home/tgeorgom/mambaforge/envs/b2e2f4bf24a083420c2c5ec8d4eef753/lib/libopenblasp-r0.3.27.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] fansi_0.4.2      withr_2.4.2      dplyr_1.0.2      crayon_1.4.1
 [5] utf8_1.2.1       grid_3.6.3       R6_2.5.0         lifecycle_1.0.0
 [9] gtable_0.3.0     magrittr_2.0.1   scales_1.1.1     pillar_1.6.1
[13] rlang_0.4.11     lazyeval_0.2.2   generics_0.1.0   vctrs_0.3.8
[17] ellipsis_0.3.2   glue_1.4.2       purrr_0.3.4      munsell_0.5.0
[21] compiler_3.6.3   pkgconfig_2.0.3  colorspace_2.0-1 tidyselect_1.1.1
[25] tibble_3.1.2
```

**Comment by katsikora** [comment]
Hi,

I'm closing this issue. Feel free to reopen if it happens with newer snakePipes versions.
