### ISSUE TITLE
createIndices caused errors

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#277]
Hi all,
Running `createIndices` in the below way I got:

- Failed to create temp dir under temp path prefix (snakePipes-tmp)! 
- Permission denied: '/package'  

```
snakepipes> createIndices --genomeURL /scratch/waterhouse_team/benth/dbg2olc-40x/scaffolds_FINAL.fasta -o snakePipes-output --tempdir snakePipes-tmp dbg2olc-40x

Failed to create temp dir under temp path prefix (snakePipes-tmp)! Try fallback: /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes-output/ ...
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/__init__.py", line 544, in snakemake
    export_cwl=export_cwl)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/workflow.py", line 407, in execute
    list_params_changes or list_untracked or delete_all_output or delete_temp_output)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/persistence.py", line 59, in __init__
    os.makedirs(d, exist_ok=True)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!
```

Thank you in advance,

Best wishes,

Michal

**Comment by steffenheyne** [comment]
Hi Michal,

I think you have not create your specific envs and the workflow uses "our" default to locate the envs. You you need to create some envs first, at least the something like 

`snakePipes  createEnvs --only CONDA_CREATE_INDEX_ENV`

see here: https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#conda

then run the createIndices workflow!

steffen

**Comment by mictadlo** [comment]
Hi,
I  used the following commands before running `createIndices`:

```
conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes
snakePipes createEnvs
```

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
I have just modified `vim snakePipes/shared/defaults.yaml` and everything the above problem disappeared
