### ISSUE TITLE
AttributeError: module 'snakePipes.common_functions' has no attribute 'handleUserArgs'

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#346]
Hi,
This command `createIndices --local -j 8 --genomeURL /scratch/waterhouse_team/benth/dbg2olc-40x/salsa/scaffolds_FINAL.fasta -o snakePipes-output --tempdir snakePipes-tmp dbg2olc40x` caused:

```
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/bin/createIndices", line 105, in <module>
    main()
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/bin/createIndices", line 75, in main
    args, defaults = cf.handleUserArgs(args, defaults, parse_args)
AttributeError: module 'snakePipes.common_functions' has no attribute 'handleUserArgs'
```

What did I miss?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
Can you try a variant of the following and let me know if you get the same error?

`createIndices -o /data/processing/ryan/indicesTest --genomeURL ftp://ftp.ensembl.org/pub/release-94/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.dna_sm.toplevel.fa.gz --gtfURL ftp://ftp.ensembl.org/pub/release-94/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.94.gtf.gz blah`

Change the `-o` and you might need `--userYAML`.

**Comment by mictadlo** [comment]
Hi,
To my suprise is still version 1.0.0 running

```
createIndices --version
/work/waterhouse_team/miniconda2/envs/snakePipes/bin/createIndices 1.0.0
(snakePipes) lorencm@cl4n007:/scratch/waterhouse_team/benth/dbg2olc-40x/snakePipes> HiC --version
/work/waterhouse_team/miniconda2/envs/snakePipes/bin/HiC 1.0.0
```

despite I did the following steps:

```
  680  conda remove --name snakePipes --all
  681  conda remove --name 44b768fd0105be6f28e8095bdc877669 --all
  682  conda info --envs
  683  conda remove --name c7f7941d54d6f48a95e3df9ae7fdb9d7 --all
  684  conda info --envs
  685  conda remove --name d2c0c8867263cf473f525d6312fd337d --all
  686  conda info --envs
  687  conda remove --name 818d5b9f15995bab0f136fb2682ef0fe --all
  688  conda info --envs
  689  conda remove --name 4e2dcc30131a02508c1dba979ebd0e75 --all
  690  conda info --envs
  691  conda remove --name 6205e58d27ba070cab9eb16234e4d87a --all
  692  conda info --envs
  693  conda remove --name 7659bc51e76c8d5ff4043bb440d0313c --all
  694  ls -hlatr
  695  conda info --envs
  696  conda remove --name 12bda8a8a8c00c677f88c9803e82d776 --all
  697  conda info --envs
  698  conda remove --name 6b81b7150e6577c3bc468b8f356eec05 --all
  699  conda info --envs
  700  conda remove --name 7c0866c4adb550bc5a2db7a030b73179 --all
  701  conda info --envsq
```

Next, yesterday I did:

```
conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes
source activate snakePipes
snakePipes createEnvs
``` 

I tried your command and got the same problem:

```
> createIndices -o /data/processing/ryan/indicesTest --genomeURL ftp://ftp.ensembl.org/pub/release-94/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.dna_sm.toplevel.fa.gz --gtfURL ftp://ftp.ensembl.org/pub/release-94/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.94.gtf.gz blah

Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/bin/createIndices", line 105, in <module>
    main()
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/bin/createIndices", line 75, in main
    args, defaults = cf.handleUserArgs(args, defaults, parse_args)
AttributeError: module 'snakePipes.common_functions' has no attribute 'handleUserArgs'
```

What did I miss?

Thank you in advance.

Michal

**Comment by dpryan79** [comment]
Can you type the following?

    python -c "from snakePipes import common_functions; print(common_functions.__file__)"

Also, what does `python --version` report?

**Comment by mictadlo** [comment]
```
python -c "from snakePipes import common_functions; print(common_functions.__file__)"
/home/lorencm/.local/lib/python3.6/site-packages/snakePipes/common_functions.py
```

```
python --version
Python 3.6.7
```

**Comment by dpryan79** [comment]
That explains it. Please `rm -rf /home/lorencm/.local/lib/python3.6/site-packages/snakePipe*`

**Comment by mictadlo** [comment]
Thank you it works.
