### ISSUE TITLE
Permission denied: '/package'

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#349]
Hi,

```
 createIndices --local -j 8 --genomeURL /scratch/waterhouse_team/benth/dbg2olc-40x/salsa/scaffolds_FINAL.fasta -o snakePipes-output --tempdir snakePipes-tmp dbg2olc40x

Failed to create temp dir under temp path prefix (snakePipes-tmp)! Try fallback: /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakePipes/snakePipes-output/ ...
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/__init__.py", line 544, in snakemake
    export_cwl=export_cwl)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/workflow.py", line 407, in execute
    list_params_changes or list_untracked or delete_all_output or delete_temp_output)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakemake/persistence.py", line 59, in __init__
    os.makedirs(d, exist_ok=True)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!
```
What did I miss?

Thank you in advance,

Best wishes,

Michal

**Comment by dpryan79** [comment]
`snakePipes createEnvs`

**Comment by mictadlo** [comment]
Thank you it works.
