### ISSUE TITLE
Problem in snakePipes createEnvs: GATK failed

### ISSUE THREAD

**Issue by yzhaowei** [maxplanck-ie/snakepipes#447]
`snakePipes createEnvs ` failed when install GATK as following. Ubuntu and Redhat 7 were both tested and got the same result. Does this problem affect downstream workflow? Is there a way to manual create a conda environment for GATK?

````
--2019-05-30 21:23:59--  https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.5-0-g36282e4
Resolving software.broadinstitute.org (software.broadinstitute.org)... 69.173.92.37
Connecting to software.broadinstitute.org (software.broadinstitute.org)|69.173.92.37|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2019-05-30 21:24:00 ERROR 500: Internal Server Error.

Traceback (most recent call last):
  File "/home/genomics/anaconda3/envs/snakePipes/bin/snakePipes", line 252, in <module>
    main(sys.argv[1:])
  File "/home/genomics/anaconda3/envs/snakePipes/bin/snakePipes", line 246, in main
    createCondaEnvs(args)
  File "/home/genomics/anaconda3/envs/snakePipes/bin/snakePipes", line 230, in createCondaEnvs
    registerGATK(gatkEnv)
  File "/home/genomics/anaconda3/envs/snakePipes/bin/snakePipes", line 134, in registerGATK
    subprocess.check_call(cmd)
  File "/home/genomics/anaconda3/envs/snakePipes/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-O', 'GATK-archive-3.5.tar.bz2', 'https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.5-0-g36282e4']' returned non-zero exit status 8.
```

**Comment by dpryan79** [comment]
Odd, the good news is that GATK is only used in the bisulfite sequencing pipeline, so unless you plan to use it this won't pose any problem.

**Comment by dpryan79** [comment]
I have now removed GATK completely from snakePipes (currently only in the develop branch).
