### ISSUE TITLE
Error in createEnvs for shared.yaml on AWS

### ISSUE THREAD

**Issue by alexgreenlon** [maxplanck-ie/snakepipes#732]
Hello,

I am trying to set up snakePipes to run on AWS. I keep getting the same error when I try to run createEnvs. I've tried on both an ubuntu (20.04) instance as well as amazon linux 2. The instances were with t2.small and a 100gb EBS SSD volume mounted. 

Here are the commands I used to try to set it up:
```
sudo mkdir /data
sudo fdisk -l
sudo mkfs -t ext4 /dev/xvdb
sudo mount /dev/xvdb /data/
sudo chown ubuntu /data
cd /data
# Get conda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p conda
export PATH=/data/conda/bin:$PATH
conda init bash
# exited to restart shell after the init step
conda config --set always_yes yes --set changeps1 no
conda update -q conda
conda create -n snakePipes -c mpi-ie -c conda-forge -c bioconda snakePipes
conda activate snakePipes
rm Miniconda3-latest-Linux-x86_64.sh

# setup snakePipes
#snakePipes createEnvs --only CONDA_SHARED_ENV CONDA_RNASEQ_ENV
snakePipes createEnvs
# got same errors with and without --only flags.
```

Here's the error:
```
Creating environment from /home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/site-packages/snakePipes/shared/rules/envs/shared.yaml in /home/ubuntu/data/conda/envs
Collecting package metadata (repodata.json): done
Solving environment: / Traceback (most recent call last):
  File "/home/ubuntu/data/conda/envs/snakePipes/bin/snakePipes", line 301, in createCondaEnvs
    subprocess.check_call(cmd)
  File "/home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--force', '--file', '/home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/site-packages/snakePipes/shared/rules/envs/shared.yaml', '--name', 'ff3148879ed9ea8da2740c156a84c2f3']' died with <Signals.SIGKILL: 9>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/data/conda/envs/snakePipes/bin/snakePipes", line 373, in <module>
    main(sys.argv[1:])
  File "/home/ubuntu/data/conda/envs/snakePipes/bin/snakePipes", line 367, in main
    createCondaEnvs(args)
  File "/home/ubuntu/data/conda/envs/snakePipes/bin/snakePipes", line 304, in createCondaEnvs
    shutil.rmtree(os.path.join(condaDirUse, h), ignore_errors=False)
  File "/home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/shutil.py", line 706, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/shutil.py", line 704, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/conda/envs/ff3148879ed9ea8da2740c156a84c2f3'
```

I get the same error when I try just the command from the snakePipes createEnv function that's giving the error:

```
conda env create --force --file /home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/site-packages/snakePipes/shared/rules/envs/shared.yaml --name ff3148879ed9ea8da2740c156a84c2f3
Collecting package metadata (repodata.json): done
Solving environment: | Killed
```
Here is the shared.yaml file:
```
name: snakepipes_shared_environment_1.0
channels:
 - conda-forge
 - bioconda
dependencies:
 - deeptools = 3.3.2
 - seqtk = 1.3
 - pigz = 2.3.4
 - snpsplit = 0.3.4
 - samtools = 1.10
 - fastqc = 0.11.9
 - cutadapt = 2.8
 - trim-galore = 0.6.5
 - multiqc = 1.8
 - fastp = 0.20.0
 - umi_tools = 1.0.1
```

I don't get any errors when I try to manually install any other functions:

```
conda env create --force --file /home/ubuntu/data/conda/envs/snakePipes/lib/python3.8/site-packages/snakePipes/shared/rules/envs/wgbs.yaml --name wgbs
```

I am actually mostly interested in the wgbs function. Can I run it successfully with just that installation?

**Comment by katsikora** [comment]
Hi,

You will need the shared environment, and I think the sambamba environment, on top on the wgbs-specific one, to run WGBS workflow.

It looks like creating the shared environment is killed by your host. This is our largest env. Can you give your VM more memory?

See e.g. https://stackoverflow.com/questions/64821441/collecting-package-metadata-repodata-json-killed

**Comment by alexgreenlon** [comment]
Thanks @katsikora I used a t2.large instance with 8 gb RAM and the installation ran to completion. 

I suggest the snakePipes team revise the help pages about installing on AWS to reflect this requirement (https://snakepipes.readthedocs.io/en/latest/content/advanced_usage.html), which specifically suggest a t2.micro instance with 2gb RAM, which was inadequate.
