### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by vitaly001** [maxplanck-ie/snakepipes#745]
Hi,
After updating snakePipes to the 2.4.2 version on MacOS BigSur I got next error:
(snakePipes) ~ $ DNA-mapping -i /Volumes/HD2/ChIP/ChIPseq  -o /Volumes/HD2/ChIP --mapq 5 --local -j 10 --dedup hg38

---- This analysis has been done using snakePipes version 2.4.2 ----
Traceback (most recent call last):
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakemake/__init__.py", line 622, in snakemake
    success = workflow.execute(
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakemake/workflow.py", line 614, in execute
    self.persistence = Persistence(
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakemake/persistence.py", line 72, in __init__
    os.makedirs(d, exist_ok=True)
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/user1/miniconda3/envs/snakePipes/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!

I know that the problem in permission to the folder, and I can set writable permission with chmod -R, however I do not understand which folder has this restrictions.
Thanks

**Comment by LeilyR** [comment]
The folder is called `/package` if you have no folder with that name I suspect you may have not changed the conda prefix path in the defaults.yaml

**Comment by LeilyR** [comment]
I hope your problem has been already solved. I close this issue for now. Feel free to reopen it, if there is still any problem left.
