### ISSUE TITLE
Permissions Error with persistence.py script: os.makedirs(d, exist_ok=True)   File "<frozen os>", line 215, in makedirs

### ISSUE THREAD

**Issue by Batsi-vai** [maxplanck-ie/snakepipes#870]
hi,

I am having some trouble running the DNA-mapping. This is the command I am using:

    $ DNA-mapping -i data -o mapping_results mm10_gencodeM19

I am getting the following error:

```
cat DNA-mapping_run-1.log 
/path_to_files/opt/miniconda3/envs/snakePipes/bin/DNA-mapping -i data_renamed/ -o mapping_results mm10_gencodeM19

TMPDIR=/data/extended/ PYTHONNOUSERSITE=True /path_to_files/opt/miniconda3/envs/snakePipes/bin/snakemake --use-conda --conda-prefix /package/anaconda3/envs/ --latency-wait 300 --snakefile /path_to_files/opt/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --jobs 5 --directory /path_to_data_analysis_folder/kdm5c_ATAC/mapping_results --configfile /path_to_data_analysis_folder/kdm5c_ATAC/mapping_results/DNA-mapping.config.yaml --keep-going --cluster-config /path_to_data_analysis_folder/kdm5c_ATAC/mapping_results/DNA-mapping.cluster_config.yaml --cluster 'module load slurm; sbatch --ntasks-per-node 1 -p bioinfo --mem-per-cpu {cluster.memory} -c {threads} -e cluster_logs/{rule}.%j.err -o cluster_logs/{rule}.%j.out -J {rule}.snakemake '


---- This analysis has been done using snakePipes version 2.7.1 ----
Traceback (most recent call last):
  File "/path_to_files/opt/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakemake/__init__.py", line 747, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/path_to_files/opt/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakemake/workflow.py", line 690, in execute
    self.persistence = Persistence(
                       ^^^^^^^^^^^^
  File "/path_to_files/opt/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakemake/persistence.py", line 100, in __init__
    os.makedirs(d, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/package'

```

**Comment by LeilyR** [comment]
You need to fix the path to your conda: `--conda-prefix /package/anaconda3/envs` 
Set it to what actually your conda path is and get sure you have write permission there.
