### ISSUE TITLE
snakePipes createEnvs raises FileNotFoundError

### ISSUE THREAD

**Issue by half-adder** [maxplanck-ie/snakepipes#874]
I followed the install directions exactly and got the following output (note, this is the second time running the command with the same error, which is why you don't see download output - many of the packages are already cached I believe):

```
(snakePipes) seanjohn@DESKTOP-K1252K3:/mnt/c/Users/Sean/Downloads$ snakePipes createEnvs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/shared.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/createIndices.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/rna_seq.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sleuth.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/rMats.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sc_rna_seq.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_seurat.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_loompy.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_alevinqc.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_eisaR.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/dna_mapping.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/chip_seq.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/atac_seq.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/hic.yaml in /home/seanjohn/miniconda3/envs
Creating environment from /home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/wgbs.yaml in /home/seanjohn/miniconda3/envs
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
mpi-ie/linux-64                                               No change
mpi-ie/noarch                                                 No change


Looking for: ['bwameth=0.2.5', 'bwa-mem2=2.2.1', 'samtools', 'methyldackel=0.6.1', 'metilene=0.2.8', 'bedtools=2.30.0', 'r-base=4.1.3', 'r-car', 'r-factominer', 'r-ggplot2', 'r-rmarkdown', 'r-dplyr', 'r-tidyr', 'r-pander', 'r-factominer', 'bioconductor-bsseq', 'bioconductor-genomicranges', 'bioconductor-genomicfeatures', 'bioconductor-biomart', 'bioconductor-dss', 'bioconductor-dmrseq', 'bioconductor-rtracklayer', 'bioconductor-biocparallel']


Encountered problems while solving:
  - package bioconductor-biomart-2.38.0-r351_0 requires r-base >=3.5.1,<3.5.2.0a0, but none of the providers can be installed

Traceback (most recent call last):
  File "/home/seanjohn/miniconda3/envs/snakePipes/bin/snakePipes", line 377, in createCondaEnvs
    subprocess.check_call(cmd)
  File "/home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mamba', 'env', 'create', '--force', '--file', '/home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/site-packages/snakePipes/shared/rules/envs/wgbs.yaml', '--name', 'f44c3494406ecd475e599c50fd4ada88']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seanjohn/miniconda3/envs/snakePipes/bin/snakePipes", line 460, in <module>
    main(sys.argv[1:])
  File "/home/seanjohn/miniconda3/envs/snakePipes/bin/snakePipes", line 454, in main
    createCondaEnvs(args)
  File "/home/seanjohn/miniconda3/envs/snakePipes/bin/snakePipes", line 380, in createCondaEnvs
    shutil.rmtree(os.path.join(condaDirUse, h), ignore_errors=False)
  File "/home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/shutil.py", line 721, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/seanjohn/miniconda3/envs/snakePipes/lib/python3.11/shutil.py", line 719, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/seanjohn/miniconda3/envs/f44c3494406ecd475e599c50fd4ada88'
```

I am using WSL if that matters

**Comment by half-adder** [comment]
It looks like it's a problem with the r-base version required?

**Comment by half-adder** [comment]
I nuked my conda installation by deleting everything and re-installing, and that solved the problem.
