### ISSUE TITLE
DAG printing breaks for ChIP-seq with --cutntag --useSpikeInForNorm

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#890]
<code>
Building DAG of jobs...
Error: <stdin>: syntax error in line 2 near 'Spikein'
Traceback (most recent call last):
  File "/package/mamba/envs/snakePipes-2.7.2/bin/ChIP-seq", line 193, in <module>
    main()
  File "/package/mamba/envs/snakePipes-2.7.2/bin/ChIP-seq", line 189, in main
    cf.print_DAG(args,snakemake_cmd, __file__,defaults)
  File "/package/mamba/envs/snakePipes-2.7.2/lib/python3.11/site-packages/snakePipes/common_functions.py", line 664, in print_DAG
    subprocess.check_call("dot -Tpdf -o{}/{}_pipeline.pdf".format(args.outdir, workflowName), stdin=DAGproc.stdout, shell=True)
  File "/package/mamba/envs/snakePipes-2.7.2/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dot -Tpdf -o/data/manke/processing/sikora/snakepipes_cutntag/analysis/ChIP-seq_pipeline.pdf' returned non-zero exit status 1.
</code>

**Comment by katsikora** [comment]
importing logging to solve this doubles the main log output
