### ISSUE TITLE
createIndices error

### ISSUE THREAD

**Issue by ppswang** [maxplanck-ie/snakepipes#954]
Hi,

I think I had no problems with installation and "createEnvs", but I had issues with createIndices:

```
$ createIndices --output-dir /WGBS/sheep_oviAri4 --genomeURL /reference/source_reference/sheep/oviAri4/ucsc_dataset/GCF_016772045.1.fa.gz --gtfURL /reference/source_reference/sheep/oviAri4/ucsc_dataset/GCF_016772045.1_ARS-UI_Ramb_v2.0.ncbiRefSeq.gtf.gz --local oviAri4
```

And this was the output:

```
---- This analysis has been done using snakePipes version 2.7.3 ----
/hpc/capacity/tools/testing/WGBS_pipelines/snakePipes/env/lib/python3.12/site-packages/snakePipes/shared/rules/createIndices.snakefile:83: SyntaxWarning: invalid escape sequence '\s'
  output: genome_dict
/hpc/capacity/tools/testing/WGBS_pipelines/snakePipes/env/lib/python3.12/site-packages/snakePipes/shared/rules/createIndices.snakefile:90: SyntaxWarning: invalid escape sequence '\s'
  if rmsk_file:
Building DAG of jobs...
Creating conda environment /hpc/capacity/tools/testing/WGBS_pipelines/snakePipes/env/lib/python3.12/site-packages/snakePipes/shared/rules/envs/shared.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /hpc/capacity/tools/testing/WGBS_pipelines/snakePipes/env/lib/python3.12/site-packages/snakePipes/shared/rules/envs/shared.yaml:
Command:
mamba env create --quiet --file "/cancer/storage/tools/testing/WGBS_pipelines/snakePipes/bea17d1e160562910abd1e19decf508a_.yaml" --prefix "/cancer/storage/tools/testing/WGBS_pipelines/snakePipes/bea17d1e160562910abd1e19decf508a_"
Output:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 162, in execute
        result[installer_type] = installer.install(
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/mamba/mamba_env.py", line 54, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
        index = get_index(
      File "/hpc/vnx_homes/paul.wang/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 85, in get_index
        sd = api.SubdirData(
    libmambapy.bindings.MambaNativeException: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

`$ /hpc/vnx_homes/paul.wang/mambaforge/condabin/mamba create --quiet --file /cancer/storage/tools/testing/WGBS_pipelines/snakePipes/bea17d1e160562910abd1e19decf508a_.yaml --prefix /cancer/storage/tools/testing/WGBS_pipelines/snakePipes/bea17d1e160562910abd1e19decf508a_`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=/hpc/capacity/tools/testing/WGBS_pipelines/snakePipes/env
                CONDA_EXE=/hpc/vnx_homes/paul.wang/mambaforge/bin/conda
.
.
.


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>


Error: snakemake returned an error code of 1, so processing is incomplete!
```

**Comment by katsikora** [comment]
Hi Ppswang,

it looks like `createIndices` attempted to (re)create the shared conda env and some sort of error occured.

How did you run `snakePipes createEnvs` ? Did you also run `snakePipes config` after the installation, passing the path to the folder you intended to createEnvs in to `snakemakeOptions` ?

Best wishes,

Katarzyna

**Comment by katsikora** [comment]
Hi, I'm closing this for lack of activity, feel free to reopen if needed.
