### ISSUE TITLE
error in createIndices: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#991]
I am on the latest developmental brach as created by cloning the github here and using the instruction on 
It is not related to #932
I am trying to create the indices/indexes for the mm39 and I stabled on the following error:
```
(/scratch/tgeorgom/mamba/snakepipes_devel) [tgeorgom@cheops1:~]$ 13:28:14$createIndices -o assemblies/mm39 --genomeURL /home/tgeorgom/assemblies/mm39/mm39.fa.gz --gtfURL  /home/tgeorgom/assemblies/mm39/mm39.knownGene.gtf.gz  -j 10 --tools 'all' --blacklist /home/tgeorgom/assemblies/mm39/mm39.excluderanges.bed --ignoreForNormalization /home/tgeorgom/assemblies/mm39/ignorefornormalisation.ext mm39 Traceback (most recent call last):
  File "/scratch/tgeorgom/mamba/snakepipes_devel/bin/snakemake", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/scratch/tgeorgom/mamba/snakepipes_devel/lib/python3.11/site-packages/snakemake/__init__.py", line 2522, in main
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tgeorgom/mamba/snakepipes_devel/lib/python3.11/site-packages/snakemake/__init__.py", line 1469, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
                 ^^^^^^^^^^^^^^^^^
AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?
Error: snakemake returned an error code of 1, so processing is incomplete!
```
Any idea?
Thank you

**Comment by WardDeb** [comment]
How exactly did you install the requirements ? This seems a mismatch between snakemake & pulp versions

**Comment by sunta3iouxos** [comment]
> How exactly did you install the requirements ? This seems a mismatch between snakemake & pulp versions

This is related to:
https://github.com/snakemake/snakemake/issues/2606

I fixed it by doing:
```
pip install --upgrade pulp==2.7.0
```
